// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crawlfrontier/contrib/backends/hbase-queue.proto

package com.scrapinghub.frontera.hbasestats;

public final class HbaseQueue {
  private HbaseQueue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QueueItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueueItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    boolean hasFingerprint();
    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    com.google.protobuf.ByteString getFingerprint();

    /**
     * <code>required sint32 host_crc32 = 2;</code>
     */
    boolean hasHostCrc32();
    /**
     * <code>required sint32 host_crc32 = 2;</code>
     */
    int getHostCrc32();

    /**
     * <code>required string url = 3;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 3;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 3;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional float score = 4;</code>
     */
    boolean hasScore();
    /**
     * <code>optional float score = 4;</code>
     */
    float getScore();
  }
  /**
   * Protobuf type {@code QueueItem}
   */
  public static final class QueueItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QueueItem)
      QueueItemOrBuilder {
    // Use QueueItem.newBuilder() to construct.
    private QueueItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueueItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueueItem defaultInstance;
    public static QueueItem getDefaultInstance() {
      return defaultInstance;
    }

    public QueueItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueueItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fingerprint_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hostCrc32_ = input.readSInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              url_ = bs;
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              score_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.class, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder.class);
    }

    public static com.google.protobuf.Parser<QueueItem> PARSER =
        new com.google.protobuf.AbstractParser<QueueItem>() {
      public QueueItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueueItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QueueItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FINGERPRINT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString fingerprint_;
    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    public boolean hasFingerprint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    public com.google.protobuf.ByteString getFingerprint() {
      return fingerprint_;
    }

    public static final int HOST_CRC32_FIELD_NUMBER = 2;
    private int hostCrc32_;
    /**
     * <code>required sint32 host_crc32 = 2;</code>
     */
    public boolean hasHostCrc32() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required sint32 host_crc32 = 2;</code>
     */
    public int getHostCrc32() {
      return hostCrc32_;
    }

    public static final int URL_FIELD_NUMBER = 3;
    private java.lang.Object url_;
    /**
     * <code>required string url = 3;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string url = 3;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 4;
    private float score_;
    /**
     * <code>optional float score = 4;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float score = 4;</code>
     */
    public float getScore() {
      return score_;
    }

    private void initFields() {
      fingerprint_ = com.google.protobuf.ByteString.EMPTY;
      hostCrc32_ = 0;
      url_ = "";
      score_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFingerprint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHostCrc32()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, fingerprint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, hostCrc32_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, fingerprint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, hostCrc32_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueueItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueueItem)
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.class, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder.class);
      }

      // Construct using com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fingerprint_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        hostCrc32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueItem_descriptor;
      }

      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem getDefaultInstanceForType() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.getDefaultInstance();
      }

      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem build() {
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem buildPartial() {
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem result = new com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fingerprint_ = fingerprint_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hostCrc32_ = hostCrc32_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem) {
          return mergeFrom((com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem other) {
        if (other == com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.getDefaultInstance()) return this;
        if (other.hasFingerprint()) {
          setFingerprint(other.getFingerprint());
        }
        if (other.hasHostCrc32()) {
          setHostCrc32(other.getHostCrc32());
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000004;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFingerprint()) {
          
          return false;
        }
        if (!hasHostCrc32()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString fingerprint_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public boolean hasFingerprint() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public com.google.protobuf.ByteString getFingerprint() {
        return fingerprint_;
      }
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public Builder setFingerprint(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fingerprint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public Builder clearFingerprint() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fingerprint_ = getDefaultInstance().getFingerprint();
        onChanged();
        return this;
      }

      private int hostCrc32_ ;
      /**
       * <code>required sint32 host_crc32 = 2;</code>
       */
      public boolean hasHostCrc32() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sint32 host_crc32 = 2;</code>
       */
      public int getHostCrc32() {
        return hostCrc32_;
      }
      /**
       * <code>required sint32 host_crc32 = 2;</code>
       */
      public Builder setHostCrc32(int value) {
        bitField0_ |= 0x00000002;
        hostCrc32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 host_crc32 = 2;</code>
       */
      public Builder clearHostCrc32() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hostCrc32_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>required string url = 3;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string url = 3;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 3;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 3;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 3;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>optional float score = 4;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float score = 4;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>optional float score = 4;</code>
       */
      public Builder setScore(float value) {
        bitField0_ |= 0x00000008;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float score = 4;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QueueItem)
    }

    static {
      defaultInstance = new QueueItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QueueItem)
  }

  public interface QueueCellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueueCell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    java.util.List<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem> 
        getItemsList();
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem getItems(int index);
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    java.util.List<? extends com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code QueueCell}
   */
  public static final class QueueCell extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QueueCell)
      QueueCellOrBuilder {
    // Use QueueCell.newBuilder() to construct.
    private QueueCell(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueueCell(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueueCell defaultInstance;
    public static QueueCell getDefaultInstance() {
      return defaultInstance;
    }

    public QueueCell getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueueCell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueCell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueCell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.class, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.Builder.class);
    }

    public static com.google.protobuf.Parser<QueueCell> PARSER =
        new com.google.protobuf.AbstractParser<QueueCell>() {
      public QueueCell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueueCell(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QueueCell> getParserForType() {
      return PARSER;
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem> items_;
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    public java.util.List<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    public java.util.List<? extends com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .QueueItem items = 1;</code>
     */
    public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueueCell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueueCell)
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueCell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueCell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.class, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.Builder.class);
      }

      // Construct using com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.internal_static_QueueCell_descriptor;
      }

      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell getDefaultInstanceForType() {
        return com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.getDefaultInstance();
      }

      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell build() {
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell buildPartial() {
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell result = new com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell) {
          return mergeFrom((com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell other) {
        if (other == com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueCell) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public java.util.List<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder addItems(com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder addItems(
          com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public java.util.List<? extends com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.getDefaultInstance());
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.getDefaultInstance());
      }
      /**
       * <code>repeated .QueueItem items = 1;</code>
       */
      public java.util.List<com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItem.Builder, com.scrapinghub.frontera.hbasestats.HbaseQueue.QueueItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:QueueCell)
    }

    static {
      defaultInstance = new QueueCell(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QueueCell)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueueItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueueItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueueCell_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueueCell_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0crawlfrontier/contrib/backends/hbase-q" +
      "ueue.proto\"P\n\tQueueItem\022\023\n\013fingerprint\030\001" +
      " \002(\014\022\022\n\nhost_crc32\030\002 \002(\021\022\013\n\003url\030\003 \002(\t\022\r\n" +
      "\005score\030\004 \001(\002\"&\n\tQueueCell\022\031\n\005items\030\001 \003(\013" +
      "2\n.QueueItemB1\n#com.scrapinghub.frontera" +
      ".hbasestatsB\nHbaseQueue"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueueItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueueItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueueItem_descriptor,
        new java.lang.String[] { "Fingerprint", "HostCrc32", "Url", "Score", });
    internal_static_QueueCell_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QueueCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueueCell_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
