// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.scrapinghub.frontera.hbasestats;

public final class MetadataOuter {
  private MetadataOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DocumentMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hbasestats.DocumentMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    boolean hasFingerprint();
    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    com.google.protobuf.ByteString getFingerprint();

    /**
     * <code>optional string url = 2;</code>
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 2;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional int32 depth = 3;</code>
     */
    boolean hasDepth();
    /**
     * <code>optional int32 depth = 3;</code>
     */
    int getDepth();

    /**
     * <code>optional uint64 created_at = 4;</code>
     */
    boolean hasCreatedAt();
    /**
     * <code>optional uint64 created_at = 4;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int32 status_code = 5;</code>
     */
    boolean hasStatusCode();
    /**
     * <code>optional int32 status_code = 5;</code>
     */
    int getStatusCode();

    /**
     * <code>optional int32 state = 6;</code>
     */
    boolean hasState();
    /**
     * <code>optional int32 state = 6;</code>
     */
    int getState();

    /**
     * <code>optional string error = 7;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 7;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 7;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <code>optional string domain_fingerprint = 8;</code>
     */
    boolean hasDomainFingerprint();
    /**
     * <code>optional string domain_fingerprint = 8;</code>
     */
    java.lang.String getDomainFingerprint();
    /**
     * <code>optional string domain_fingerprint = 8;</code>
     */
    com.google.protobuf.ByteString
        getDomainFingerprintBytes();

    /**
     * <code>optional float score = 9;</code>
     */
    boolean hasScore();
    /**
     * <code>optional float score = 9;</code>
     */
    float getScore();
  }
  /**
   * Protobuf type {@code hbasestats.DocumentMetadata}
   */
  public static final class DocumentMetadata extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hbasestats.DocumentMetadata)
      DocumentMetadataOrBuilder {
    // Use DocumentMetadata.newBuilder() to construct.
    private DocumentMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DocumentMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DocumentMetadata defaultInstance;
    public static DocumentMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public DocumentMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DocumentMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fingerprint_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              url_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              depth_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createdAt_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              statusCode_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              state_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              error_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              domainFingerprint_ = bs;
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              score_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_DocumentMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_DocumentMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.class, com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<DocumentMetadata> PARSER =
        new com.google.protobuf.AbstractParser<DocumentMetadata>() {
      public DocumentMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DocumentMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DocumentMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FINGERPRINT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString fingerprint_;
    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    public boolean hasFingerprint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes fingerprint = 1;</code>
     */
    public com.google.protobuf.ByteString getFingerprint() {
      return fingerprint_;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private java.lang.Object url_;
    /**
     * <code>optional string url = 2;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string url = 2;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPTH_FIELD_NUMBER = 3;
    private int depth_;
    /**
     * <code>optional int32 depth = 3;</code>
     */
    public boolean hasDepth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 depth = 3;</code>
     */
    public int getDepth() {
      return depth_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 4;
    private long createdAt_;
    /**
     * <code>optional uint64 created_at = 4;</code>
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 created_at = 4;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    public static final int STATUS_CODE_FIELD_NUMBER = 5;
    private int statusCode_;
    /**
     * <code>optional int32 status_code = 5;</code>
     */
    public boolean hasStatusCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 status_code = 5;</code>
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int STATE_FIELD_NUMBER = 6;
    private int state_;
    /**
     * <code>optional int32 state = 6;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 state = 6;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int ERROR_FIELD_NUMBER = 7;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 7;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string error = 7;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 7;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAIN_FINGERPRINT_FIELD_NUMBER = 8;
    private java.lang.Object domainFingerprint_;
    /**
     * <code>optional string domain_fingerprint = 8;</code>
     */
    public boolean hasDomainFingerprint() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string domain_fingerprint = 8;</code>
     */
    public java.lang.String getDomainFingerprint() {
      java.lang.Object ref = domainFingerprint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domainFingerprint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string domain_fingerprint = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDomainFingerprintBytes() {
      java.lang.Object ref = domainFingerprint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domainFingerprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 9;
    private float score_;
    /**
     * <code>optional float score = 9;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional float score = 9;</code>
     */
    public float getScore() {
      return score_;
    }

    private void initFields() {
      fingerprint_ = com.google.protobuf.ByteString.EMPTY;
      url_ = "";
      depth_ = 0;
      createdAt_ = 0L;
      statusCode_ = 0;
      state_ = 0;
      error_ = "";
      domainFingerprint_ = "";
      score_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFingerprint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, fingerprint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, depth_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, createdAt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, statusCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, state_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getErrorBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getDomainFingerprintBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(9, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, fingerprint_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, depth_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, createdAt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, statusCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, state_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getErrorBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDomainFingerprintBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbasestats.DocumentMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hbasestats.DocumentMetadata)
        com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_DocumentMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_DocumentMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.class, com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.Builder.class);
      }

      // Construct using com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fingerprint_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        depth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        createdAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        statusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        domainFingerprint_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        score_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_DocumentMetadata_descriptor;
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata getDefaultInstanceForType() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.getDefaultInstance();
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata build() {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata buildPartial() {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata result = new com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fingerprint_ = fingerprint_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.depth_ = depth_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createdAt_ = createdAt_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.statusCode_ = statusCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.domainFingerprint_ = domainFingerprint_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata) {
          return mergeFrom((com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata other) {
        if (other == com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata.getDefaultInstance()) return this;
        if (other.hasFingerprint()) {
          setFingerprint(other.getFingerprint());
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000002;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasDepth()) {
          setDepth(other.getDepth());
        }
        if (other.hasCreatedAt()) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000040;
          error_ = other.error_;
          onChanged();
        }
        if (other.hasDomainFingerprint()) {
          bitField0_ |= 0x00000080;
          domainFingerprint_ = other.domainFingerprint_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFingerprint()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scrapinghub.frontera.hbasestats.MetadataOuter.DocumentMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString fingerprint_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public boolean hasFingerprint() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public com.google.protobuf.ByteString getFingerprint() {
        return fingerprint_;
      }
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public Builder setFingerprint(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fingerprint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes fingerprint = 1;</code>
       */
      public Builder clearFingerprint() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fingerprint_ = getDefaultInstance().getFingerprint();
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 2;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string url = 2;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 2;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 2;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
        return this;
      }

      private int depth_ ;
      /**
       * <code>optional int32 depth = 3;</code>
       */
      public boolean hasDepth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 depth = 3;</code>
       */
      public int getDepth() {
        return depth_;
      }
      /**
       * <code>optional int32 depth = 3;</code>
       */
      public Builder setDepth(int value) {
        bitField0_ |= 0x00000004;
        depth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 depth = 3;</code>
       */
      public Builder clearDepth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        depth_ = 0;
        onChanged();
        return this;
      }

      private long createdAt_ ;
      /**
       * <code>optional uint64 created_at = 4;</code>
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 created_at = 4;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <code>optional uint64 created_at = 4;</code>
       */
      public Builder setCreatedAt(long value) {
        bitField0_ |= 0x00000008;
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 created_at = 4;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>optional int32 status_code = 5;</code>
       */
      public boolean hasStatusCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 status_code = 5;</code>
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>optional int32 status_code = 5;</code>
       */
      public Builder setStatusCode(int value) {
        bitField0_ |= 0x00000010;
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status_code = 5;</code>
       */
      public Builder clearStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>optional int32 state = 6;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 state = 6;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>optional int32 state = 6;</code>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000020;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 state = 6;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000020);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 7;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            error_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000040);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        error_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domainFingerprint_ = "";
      /**
       * <code>optional string domain_fingerprint = 8;</code>
       */
      public boolean hasDomainFingerprint() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string domain_fingerprint = 8;</code>
       */
      public java.lang.String getDomainFingerprint() {
        java.lang.Object ref = domainFingerprint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            domainFingerprint_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string domain_fingerprint = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDomainFingerprintBytes() {
        java.lang.Object ref = domainFingerprint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domainFingerprint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string domain_fingerprint = 8;</code>
       */
      public Builder setDomainFingerprint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        domainFingerprint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain_fingerprint = 8;</code>
       */
      public Builder clearDomainFingerprint() {
        bitField0_ = (bitField0_ & ~0x00000080);
        domainFingerprint_ = getDefaultInstance().getDomainFingerprint();
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain_fingerprint = 8;</code>
       */
      public Builder setDomainFingerprintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        domainFingerprint_ = value;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>optional float score = 9;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional float score = 9;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>optional float score = 9;</code>
       */
      public Builder setScore(float value) {
        bitField0_ |= 0x00000100;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float score = 9;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000100);
        score_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hbasestats.DocumentMetadata)
    }

    static {
      defaultInstance = new DocumentMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hbasestats.DocumentMetadata)
  }

  public interface HBaseCellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hbasestats.HBaseCell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes family = 1;</code>
     */
    boolean hasFamily();
    /**
     * <code>required bytes family = 1;</code>
     */
    com.google.protobuf.ByteString getFamily();

    /**
     * <code>required bytes column = 2;</code>
     */
    boolean hasColumn();
    /**
     * <code>required bytes column = 2;</code>
     */
    com.google.protobuf.ByteString getColumn();

    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>required bytes value = 4;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 4;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code hbasestats.HBaseCell}
   */
  public static final class HBaseCell extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hbasestats.HBaseCell)
      HBaseCellOrBuilder {
    // Use HBaseCell.newBuilder() to construct.
    private HBaseCell(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HBaseCell(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HBaseCell defaultInstance;
    public static HBaseCell getDefaultInstance() {
      return defaultInstance;
    }

    public HBaseCell getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HBaseCell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              family_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              column_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseCell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseCell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.class, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder.class);
    }

    public static com.google.protobuf.Parser<HBaseCell> PARSER =
        new com.google.protobuf.AbstractParser<HBaseCell>() {
      public HBaseCell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HBaseCell(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HBaseCell> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FAMILY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString family_;
    /**
     * <code>required bytes family = 1;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes family = 1;</code>
     */
    public com.google.protobuf.ByteString getFamily() {
      return family_;
    }

    public static final int COLUMN_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString column_;
    /**
     * <code>required bytes column = 2;</code>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes column = 2;</code>
     */
    public com.google.protobuf.ByteString getColumn() {
      return column_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 4;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes value = 4;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      family_ = com.google.protobuf.ByteString.EMPTY;
      column_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, family_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, column_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, family_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, column_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbasestats.HBaseCell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hbasestats.HBaseCell)
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseCell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseCell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.class, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder.class);
      }

      // Construct using com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        family_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseCell_descriptor;
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell getDefaultInstanceForType() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.getDefaultInstance();
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell build() {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell buildPartial() {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell result = new com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.family_ = family_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.column_ = column_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell) {
          return mergeFrom((com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell other) {
        if (other == com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.getDefaultInstance()) return this;
        if (other.hasFamily()) {
          setFamily(other.getFamily());
        }
        if (other.hasColumn()) {
          setColumn(other.getColumn());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFamily()) {
          
          return false;
        }
        if (!hasColumn()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString family_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes family = 1;</code>
       */
      public boolean hasFamily() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes family = 1;</code>
       */
      public com.google.protobuf.ByteString getFamily() {
        return family_;
      }
      /**
       * <code>required bytes family = 1;</code>
       */
      public Builder setFamily(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes family = 1;</code>
       */
      public Builder clearFamily() {
        bitField0_ = (bitField0_ & ~0x00000001);
        family_ = getDefaultInstance().getFamily();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString column_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes column = 2;</code>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes column = 2;</code>
       */
      public com.google.protobuf.ByteString getColumn() {
        return column_;
      }
      /**
       * <code>required bytes column = 2;</code>
       */
      public Builder setColumn(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes column = 2;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 4;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes value = 4;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 4;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 4;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hbasestats.HBaseCell)
    }

    static {
      defaultInstance = new HBaseCell(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hbasestats.HBaseCell)
  }

  public interface HBaseRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hbasestats.HBaseRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    java.util.List<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell> 
        getCellsList();
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell getCells(int index);
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    int getCellsCount();
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    java.util.List<? extends com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder> 
        getCellsOrBuilderList();
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder getCellsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hbasestats.HBaseRow}
   */
  public static final class HBaseRow extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hbasestats.HBaseRow)
      HBaseRowOrBuilder {
    // Use HBaseRow.newBuilder() to construct.
    private HBaseRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HBaseRow(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HBaseRow defaultInstance;
    public static HBaseRow getDefaultInstance() {
      return defaultInstance;
    }

    public HBaseRow getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HBaseRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cells_ = new java.util.ArrayList<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell>();
                mutable_bitField0_ |= 0x00000001;
              }
              cells_.add(input.readMessage(com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseRow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.class, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.Builder.class);
    }

    public static com.google.protobuf.Parser<HBaseRow> PARSER =
        new com.google.protobuf.AbstractParser<HBaseRow>() {
      public HBaseRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HBaseRow(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HBaseRow> getParserForType() {
      return PARSER;
    }

    public static final int CELLS_FIELD_NUMBER = 1;
    private java.util.List<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell> cells_;
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    public java.util.List<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell> getCellsList() {
      return cells_;
    }
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    public java.util.List<? extends com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder> 
        getCellsOrBuilderList() {
      return cells_;
    }
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    public int getCellsCount() {
      return cells_.size();
    }
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell getCells(int index) {
      return cells_.get(index);
    }
    /**
     * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
     */
    public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder getCellsOrBuilder(
        int index) {
      return cells_.get(index);
    }

    private void initFields() {
      cells_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCellsCount(); i++) {
        if (!getCells(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < cells_.size(); i++) {
        output.writeMessage(1, cells_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cells_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cells_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbasestats.HBaseRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hbasestats.HBaseRow)
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseRow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.class, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.Builder.class);
      }

      // Construct using com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCellsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.internal_static_hbasestats_HBaseRow_descriptor;
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow getDefaultInstanceForType() {
        return com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.getDefaultInstance();
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow build() {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow buildPartial() {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow result = new com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow(this);
        int from_bitField0_ = bitField0_;
        if (cellsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cells_ = java.util.Collections.unmodifiableList(cells_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cells_ = cells_;
        } else {
          result.cells_ = cellsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow) {
          return mergeFrom((com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow other) {
        if (other == com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow.getDefaultInstance()) return this;
        if (cellsBuilder_ == null) {
          if (!other.cells_.isEmpty()) {
            if (cells_.isEmpty()) {
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCellsIsMutable();
              cells_.addAll(other.cells_);
            }
            onChanged();
          }
        } else {
          if (!other.cells_.isEmpty()) {
            if (cellsBuilder_.isEmpty()) {
              cellsBuilder_.dispose();
              cellsBuilder_ = null;
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cellsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCellsFieldBuilder() : null;
            } else {
              cellsBuilder_.addAllMessages(other.cells_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCellsCount(); i++) {
          if (!getCells(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseRow) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell> cells_ =
        java.util.Collections.emptyList();
      private void ensureCellsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cells_ = new java.util.ArrayList<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell>(cells_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder> cellsBuilder_;

      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public java.util.List<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell> getCellsList() {
        if (cellsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cells_);
        } else {
          return cellsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public int getCellsCount() {
        if (cellsBuilder_ == null) {
          return cells_.size();
        } else {
          return cellsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell getCells(int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);
        } else {
          return cellsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder setCells(
          int index, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.set(index, value);
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder setCells(
          int index, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.set(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder addCells(com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder addCells(
          int index, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(index, value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder addCells(
          com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder addCells(
          int index, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder addAllCells(
          java.lang.Iterable<? extends com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell> values) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cells_);
          onChanged();
        } else {
          cellsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder clearCells() {
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public Builder removeCells(int index) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.remove(index);
          onChanged();
        } else {
          cellsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder getCellsBuilder(
          int index) {
        return getCellsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder getCellsOrBuilder(
          int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);  } else {
          return cellsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public java.util.List<? extends com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder> 
           getCellsOrBuilderList() {
        if (cellsBuilder_ != null) {
          return cellsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cells_);
        }
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder addCellsBuilder() {
        return getCellsFieldBuilder().addBuilder(
            com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.getDefaultInstance());
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder addCellsBuilder(
          int index) {
        return getCellsFieldBuilder().addBuilder(
            index, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.getDefaultInstance());
      }
      /**
       * <code>repeated .hbasestats.HBaseCell cells = 1;</code>
       */
      public java.util.List<com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder> 
           getCellsBuilderList() {
        return getCellsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder> 
          getCellsFieldBuilder() {
        if (cellsBuilder_ == null) {
          cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCell.Builder, com.scrapinghub.frontera.hbasestats.MetadataOuter.HBaseCellOrBuilder>(
                  cells_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cells_ = null;
        }
        return cellsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:hbasestats.HBaseRow)
    }

    static {
      defaultInstance = new HBaseRow(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hbasestats.HBaseRow)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hbasestats_DocumentMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbasestats_DocumentMetadata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hbasestats_HBaseCell_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbasestats_HBaseCell_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hbasestats_HBaseRow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbasestats_HBaseRow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016metadata.proto\022\nhbasestats\"\265\001\n\020Documen" +
      "tMetadata\022\023\n\013fingerprint\030\001 \002(\014\022\013\n\003url\030\002 " +
      "\001(\t\022\r\n\005depth\030\003 \001(\005\022\022\n\ncreated_at\030\004 \001(\004\022\023" +
      "\n\013status_code\030\005 \001(\005\022\r\n\005state\030\006 \001(\005\022\r\n\005er" +
      "ror\030\007 \001(\t\022\032\n\022domain_fingerprint\030\010 \001(\t\022\r\n" +
      "\005score\030\t \001(\002\"M\n\tHBaseCell\022\016\n\006family\030\001 \002(" +
      "\014\022\016\n\006column\030\002 \002(\014\022\021\n\ttimestamp\030\003 \002(\004\022\r\n\005" +
      "value\030\004 \002(\014\"0\n\010HBaseRow\022$\n\005cells\030\001 \003(\0132\025" +
      ".hbasestats.HBaseCellB4\n#com.scrapinghub" +
      ".frontera.hbasestatsB\rMetadataOuter"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hbasestats_DocumentMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hbasestats_DocumentMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hbasestats_DocumentMetadata_descriptor,
        new java.lang.String[] { "Fingerprint", "Url", "Depth", "CreatedAt", "StatusCode", "State", "Error", "DomainFingerprint", "Score", });
    internal_static_hbasestats_HBaseCell_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hbasestats_HBaseCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hbasestats_HBaseCell_descriptor,
        new java.lang.String[] { "Family", "Column", "Timestamp", "Value", });
    internal_static_hbasestats_HBaseRow_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hbasestats_HBaseRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hbasestats_HBaseRow_descriptor,
        new java.lang.String[] { "Cells", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
