# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hbase-queue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hbase-queue.proto',
  package='',
  serialized_pb=_b('\n\x11hbase-queue.proto\"P\n\tQueueItem\x12\x13\n\x0b\x66ingerprint\x18\x01 \x02(\x0c\x12\x12\n\nhost_crc32\x18\x02 \x02(\x11\x12\x0b\n\x03url\x18\x03 \x02(\t\x12\r\n\x05score\x18\x04 \x01(\x02\"&\n\tQueueCell\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.QueueItem')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUEUEITEM = _descriptor.Descriptor(
  name='QueueItem',
  full_name='QueueItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='QueueItem.fingerprint', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_crc32', full_name='QueueItem.host_crc32', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='QueueItem.url', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='QueueItem.score', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=101,
)


_QUEUECELL = _descriptor.Descriptor(
  name='QueueCell',
  full_name='QueueCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='QueueCell.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=141,
)

_QUEUECELL.fields_by_name['items'].message_type = _QUEUEITEM
DESCRIPTOR.message_types_by_name['QueueItem'] = _QUEUEITEM
DESCRIPTOR.message_types_by_name['QueueCell'] = _QUEUECELL

QueueItem = _reflection.GeneratedProtocolMessageType('QueueItem', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEITEM,
  __module__ = 'hbase_queue_pb2'
  # @@protoc_insertion_point(class_scope:QueueItem)
  ))
_sym_db.RegisterMessage(QueueItem)

QueueCell = _reflection.GeneratedProtocolMessageType('QueueCell', (_message.Message,), dict(
  DESCRIPTOR = _QUEUECELL,
  __module__ = 'hbase_queue_pb2'
  # @@protoc_insertion_point(class_scope:QueueCell)
  ))
_sym_db.RegisterMessage(QueueCell)


# @@protoc_insertion_point(module_scope)
